name: fresca
channels:
  - conda-forge
dependencies:
  - contextily
  - gdal
  - geopandas
  - geoviews
  - h3-py
  - hvplot
  - intake
  - jupyterlab
  - panel
  - pip
  - python=3.10
  - rapidfuzz
  - rasterio
  - shapely
  - sqlite
  - pip:
    - cf-pandas
    - intake-erddap
